## Lecture 01: Pandas

In [1]:
import numpy as pd
import pandas as pd

In [2]:
# Series: Population by Country Code
country_population = pd.Series(
     data=[61, 46, 11, 65, 10],
    index=["IT", "ES", "GR", "FR", "PO"],
    name="Country Population"
)
country_population
data = {
    "Name": [
         "Avery Bradley", "John Holland", "Jonas Jerebko",
        "Jordan Mickey", "Terry Rozier", "Jared Sullinger", "Evan Turner"
    ],
    "Team": ["Boston Celtics"] * 7,
     "Number": [0.0, 30.0, 8.0, None, 12.0, 7.0, 11.0],
     "Position": ["PG", "SG", "PF", "PF", "PG", "C", "SG"],
     "Age": [25.0, 27.0, 29.0, 21.0, 22.0, None, 27.0]
}
df_0 = pd.DataFrame(data)

In [3]:
df_0

              Name            Team  Number Position   Age
0    Avery Bradley  Boston Celtics     0.0       PG  25.0
1     John Holland  Boston Celtics    30.0       SG  27.0
2    Jonas Jerebko  Boston Celtics     8.0       PF  29.0
3    Jordan Mickey  Boston Celtics     NaN       PF  21.0
4     Terry Rozier  Boston Celtics    12.0       PG  22.0
5  Jared Sullinger  Boston Celtics     7.0        C   NaN
6      Evan Turner  Boston Celtics    11.0       SG  27.0

In [4]:
df_0.index

RangeIndex(start=0, stop=7, step=1)

In [5]:
df_0.columns

Index(['Name', 'Team', 'Number', 'Position', 'Age'], dtype='object')

In [7]:
df_0.columns[2] ='sdfsf'

TypeError: Index does not support mutable operations

In [8]:
country_population

IT    61
ES    46
GR    11
FR    65
PO    10
Name: Country Population, dtype: int64

In [10]:
country_population.index #immutable

Index(['IT', 'ES', 'GR', 'FR', 'PO'], dtype='object')

In [11]:
country_population

IT    61
ES    46
GR    11
FR    65
PO    10
Name: Country Population, dtype: int64

In [12]:
country_population[1]

C:\Users\Admin\AppData\Local\Temp\ipykernel_18592\2605600934.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  country_population[1]

np.int64(46)

In [13]:
country_population['GR']

np.int64(11)

In [14]:
country_population[:2]

IT    61
ES    46
Name: Country Population, dtype: int64

In [15]:
country_population

IT    61
ES    46
GR    11
FR    65
PO    10
Name: Country Population, dtype: int64

In [16]:
country_population[:'GR']

IT    61
ES    46
GR    11
Name: Country Population, dtype: int64

In [17]:
df_0

              Name            Team  Number Position   Age
0    Avery Bradley  Boston Celtics     0.0       PG  25.0
1     John Holland  Boston Celtics    30.0       SG  27.0
2    Jonas Jerebko  Boston Celtics     8.0       PF  29.0
3    Jordan Mickey  Boston Celtics     NaN       PF  21.0
4     Terry Rozier  Boston Celtics    12.0       PG  22.0
5  Jared Sullinger  Boston Celtics     7.0        C   NaN
6      Evan Turner  Boston Celtics    11.0       SG  27.0

In [18]:
df_0['Name']

0      Avery Bradley
1       John Holland
2      Jonas Jerebko
3      Jordan Mickey
4       Terry Rozier
5    Jared Sullinger
6        Evan Turner
Name: Name, dtype: object

In [20]:
df_0['Number']

0     0.0
1    30.0
2     8.0
3     NaN
4    12.0
5     7.0
6    11.0
Name: Number, dtype: float64

In [22]:
df_0[['Name','Number']]#fancy index

              Name  Number
0    Avery Bradley     0.0
1     John Holland    30.0
2    Jonas Jerebko     8.0
3    Jordan Mickey     NaN
4     Terry Rozier    12.0
5  Jared Sullinger     7.0
6      Evan Turner    11.0

In [23]:
df_0

              Name            Team  Number Position   Age
0    Avery Bradley  Boston Celtics     0.0       PG  25.0
1     John Holland  Boston Celtics    30.0       SG  27.0
2    Jonas Jerebko  Boston Celtics     8.0       PF  29.0
3    Jordan Mickey  Boston Celtics     NaN       PF  21.0
4     Terry Rozier  Boston Celtics    12.0       PG  22.0
5  Jared Sullinger  Boston Celtics     7.0        C   NaN
6      Evan Turner  Boston Celtics    11.0       SG  27.0

In [25]:
df_0.iloc[:2,:3]

            Name            Team  Number
0  Avery Bradley  Boston Celtics     0.0
1   John Holland  Boston Celtics    30.0

In [26]:
country_population[1]

C:\Users\Admin\AppData\Local\Temp\ipykernel_18592\2605600934.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  country_population[1]

np.int64(46)

In [27]:
country_population.iloc[1]

np.int64(46)

In [28]:
data = {'Province': ['Hanoi', 'HCMC', 'Danang'],
         'Population (millions)': [8.05, 8.99, 1.13]}
df = pd.DataFrame(data)

In [30]:
df.index = list('abc')
df

  Province  Population (millions)
a    Hanoi                   8.05
b     HCMC                   8.99
c   Danang                   1.13

In [31]:
df.iloc[0]

Province                 Hanoi
Population (millions)     8.05
Name: a, dtype: object

In [32]:
df.loc['a']

Province                 Hanoi
Population (millions)     8.05
Name: a, dtype: object

In [33]:
country_population

IT    61
ES    46
GR    11
FR    65
PO    10
Name: Country Population, dtype: int64

In [39]:
df_0[df_0['Age']>22]

            Name            Team  Number Position   Age
0  Avery Bradley  Boston Celtics     0.0       PG  25.0
1   John Holland  Boston Celtics    30.0       SG  27.0
2  Jonas Jerebko  Boston Celtics     8.0       PF  29.0
6    Evan Turner  Boston Celtics    11.0       SG  27.0

In [40]:
import seaborn as sns

In [41]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [43]:
df_lab0 = sns.load_dataset('titanic')
df_lab0.head() #default = 5

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [45]:
df_lab0['survived'].mean()

np.float64(0.3838383838383838)

In [48]:
female_ratio = df_lab0[df_lab0['sex'] == 'female']['survived'].mean()
male_ratio = df_lab0[df_lab0['sex'] == 'male']['survived'].mean()
print(female_ratio)
print(male_ratio)

0.7420382165605095
0.18890814558058924