## Lecture 2

In [3]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/ntlong-NEU/DSEB65A-DataPre-Visual/refs/heads/main/Data/OnlineRetail.csv')

In [5]:
df.head() # default = 5

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,539993,22386,JUMBO BAG PINK POLKADOT,10,2011-01-04 10:00:00,1.95,13313.0,United Kingdom
1,539993,21499,BLUE POLKADOT WRAP,25,2011-01-04 10:00:00,0.42,13313.0,United Kingdom
2,539993,21498,RED RETROSPOT WRAP,25,2011-01-04 10:00:00,0.42,13313.0,United Kingdom
3,539993,22379,RECYCLING BAG RETROSPOT,5,2011-01-04 10:00:00,2.10,13313.0,United Kingdom
4,539993,20718,RED RETROSPOT SHOPPER BAG,10,2011-01-04 10:00:00,1.25,13313.0,United Kingdom

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203422 entries, 0 to 203421
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    203422 non-null  object
 1   StockCode    203422 non-null  object
 2   Description  202623 non-null  object
 3   Quantity     203422 non-null  int64
 4   InvoiceDate  203422 non-null  object
 5   UnitPrice    203422 non-null  float64
 6   CustomerID   150039 non-null  float64
 7   Country      203422 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 12.4+ MB

In [7]:
df.describe()

            Quantity      UnitPrice     CustomerID
count  203422.000000  203422.000000  150039.000000
mean        9.585684       4.877820   15240.234832
std       240.921315     113.686676    1717.658493
min    -74215.000000       0.000000   12346.000000
25%         1.000000       1.250000   13791.000000
50%         3.000000       2.100000   15061.000000
75%        10.000000       4.130000   16771.000000
max     74215.000000   38970.000000   18287.000000

In [9]:
df.head(2)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,539993,22386,JUMBO BAG PINK POLKADOT,10,2011-01-04 10:00:00,1.95,13313.0,United Kingdom
1,539993,21499,BLUE POLKADOT WRAP,25,2011-01-04 10:00:00,0.42,13313.0,United Kingdom

In [10]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203422 entries, 0 to 203421
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    203422 non-null  object
 1   StockCode    203422 non-null  object
 2   Description  202623 non-null  object
 3   Quantity     203422 non-null  int64
 4   InvoiceDate  203422 non-null  datetime64[ns]
 5   UnitPrice    203422 non-null  float64
 6   CustomerID   150039 non-null  float64
 7   Country      203422 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 12.4+ MB

In [15]:
df.isnull().sum()

InvoiceNo          0
StockCode          0
Description      799
Quantity           0
InvoiceDate        0
UnitPrice          0
CustomerID     53383
Country            0
dtype: int64

In [21]:
df.dropna(subset=['CustomerID'], inplace=True)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 150039 entries, 0 to 203421
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    150039 non-null  object
 1   StockCode    150039 non-null  object
 2   Description  150039 non-null  object
 3   Quantity     150039 non-null  int64
 4   InvoiceDate  150039 non-null  datetime64[ns]
 5   UnitPrice    150039 non-null  float64
 6   CustomerID   150039 non-null  object
 7   Country      150039 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 10.3+ MB

In [23]:
df['CustomerID'] = df['CustomerID'].astype(int).astype(str)

In [24]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,539993,22386,JUMBO BAG PINK POLKADOT,10,2011-01-04 10:00:00,1.95,13313,United Kingdom
1,539993,21499,BLUE POLKADOT WRAP,25,2011-01-04 10:00:00,0.42,13313,United Kingdom
2,539993,21498,RED RETROSPOT WRAP,25,2011-01-04 10:00:00,0.42,13313,United Kingdom
3,539993,22379,RECYCLING BAG RETROSPOT,5,2011-01-04 10:00:00,2.10,13313,United Kingdom
4,539993,20718,RED RETROSPOT SHOPPER BAG,10,2011-01-04 10:00:00,1.25,13313,United Kingdom

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 150039 entries, 0 to 203421
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    150039 non-null  object
 1   StockCode    150039 non-null  object
 2   Description  150039 non-null  object
 3   Quantity     150039 non-null  int64
 4   InvoiceDate  150039 non-null  datetime64[ns]
 5   UnitPrice    150039 non-null  float64
 6   CustomerID   150039 non-null  object
 7   Country      150039 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 10.3+ MB

In [27]:
df.duplicated().sum()

np.int64(1490)

In [28]:
df.drop_duplicates(inplace= True)

In [29]:
df.duplicated().sum()

np.int64(0)

In [30]:
df.describe()

            Quantity                    InvoiceDate      UnitPrice
count  148549.000000                         148549  148549.000000
mean       12.623289  2011-04-06 07:37:53.255962624       3.898172
min    -74215.000000            2011-01-04 10:00:00       0.000000
25%         2.000000            2011-02-22 17:25:00       1.250000
50%         6.000000            2011-04-07 10:20:00       1.950000
75%        12.000000            2011-05-19 17:13:00       3.750000
max     74215.000000            2011-06-30 20:08:00   38970.000000
std       276.503772                            NaN     108.985534

In [34]:
df[df["Quantity"] <= 0]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
76,C540006,21306,SET/4 DAISY MIRROR MAGNETS,-1,2011-01-04 10:48:00,2.10,14606,United Kingdom
77,C540006,84352,SILVER CHRISTMAS TREE BAUBLE STAND,-1,2011-01-04 10:48:00,16.95,14606,United Kingdom
78,C540006,22423,REGENCY CAKESTAND 3 TIER,-1,2011-01-04 10:48:00,12.75,14606,United Kingdom
79,C540007,21055,TOOL BOX SOFT TOY,-6,2011-01-04 11:08:00,8.95,15379,United Kingdom
80,C540007,22274,FELTCRAFT DOLL EMILY,-6,2011-01-04 11:08:00,2.95,15379,United Kingdom
...,...,...,...,...,...,...,...,...
201945,C558531,22424,ENAMEL BREAD BIN CREAM,-1,2011-06-30 11:31:00,12.75,15039,United Kingdom
202318,C558553,23170,REGENCY TEA PLATE ROSES,-576,2011-06-30 12:44:00,1.45,17949,United Kingdom
202427,C558559,20749,ASSORTED COLOUR MINI CASES,-1,2011-06-30 13:20:00,7.95,17648,United Kingdom
202627,C558575,22693,GROW A FLYTRAP OR SUNFLOWER IN TIN,-24,2011-06-30 14:58:00,1.25,12674,France
203075,C558615,21845,DAIRY MAID STRIPE MUG,-4,2011-06-30 16:20:00,0.79,17719,United Kingdom