## Lecture 2

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/ntlong-NEU/DSEB65A-DataPre-Visual/refs/heads/main/Data/OnlineRetail.csv')

In [3]:
df.head() # default = 5

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,539993,22386,JUMBO BAG PINK POLKADOT,10,2011-01-04 10:00:00,1.95,13313.0,United Kingdom
1,539993,21499,BLUE POLKADOT WRAP,25,2011-01-04 10:00:00,0.42,13313.0,United Kingdom
2,539993,21498,RED RETROSPOT WRAP,25,2011-01-04 10:00:00,0.42,13313.0,United Kingdom
3,539993,22379,RECYCLING BAG RETROSPOT,5,2011-01-04 10:00:00,2.10,13313.0,United Kingdom
4,539993,20718,RED RETROSPOT SHOPPER BAG,10,2011-01-04 10:00:00,1.25,13313.0,United Kingdom

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203422 entries, 0 to 203421
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    203422 non-null  object
 1   StockCode    203422 non-null  object
 2   Description  202623 non-null  object
 3   Quantity     203422 non-null  int64
 4   InvoiceDate  203422 non-null  object
 5   UnitPrice    203422 non-null  float64
 6   CustomerID   150039 non-null  float64
 7   Country      203422 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 12.4+ MB

In [5]:
df.describe()

            Quantity      UnitPrice     CustomerID
count  203422.000000  203422.000000  150039.000000
mean        9.585684       4.877820   15240.234832
std       240.921315     113.686676    1717.658493
min    -74215.000000       0.000000   12346.000000
25%         1.000000       1.250000   13791.000000
50%         3.000000       2.100000   15061.000000
75%        10.000000       4.130000   16771.000000
max     74215.000000   38970.000000   18287.000000

In [6]:
df.head(2)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,539993,22386,JUMBO BAG PINK POLKADOT,10,2011-01-04 10:00:00,1.95,13313.0,United Kingdom
1,539993,21499,BLUE POLKADOT WRAP,25,2011-01-04 10:00:00,0.42,13313.0,United Kingdom

In [7]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203422 entries, 0 to 203421
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    203422 non-null  object
 1   StockCode    203422 non-null  object
 2   Description  202623 non-null  object
 3   Quantity     203422 non-null  int64
 4   InvoiceDate  203422 non-null  datetime64[ns]
 5   UnitPrice    203422 non-null  float64
 6   CustomerID   150039 non-null  float64
 7   Country      203422 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 12.4+ MB

In [8]:
df.isnull().sum()

InvoiceNo          0
StockCode          0
Description      799
Quantity           0
InvoiceDate        0
UnitPrice          0
CustomerID     53383
Country            0
dtype: int64

In [9]:
df.dropna(subset=['CustomerID'], inplace=True)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 150039 entries, 0 to 203421
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    150039 non-null  object
 1   StockCode    150039 non-null  object
 2   Description  150039 non-null  object
 3   Quantity     150039 non-null  int64
 4   InvoiceDate  150039 non-null  datetime64[ns]
 5   UnitPrice    150039 non-null  float64
 6   CustomerID   150039 non-null  float64
 7   Country      150039 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 10.3+ MB

In [11]:
df['CustomerID'] = df['CustomerID'].astype(int).astype(str)

In [12]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,539993,22386,JUMBO BAG PINK POLKADOT,10,2011-01-04 10:00:00,1.95,13313,United Kingdom
1,539993,21499,BLUE POLKADOT WRAP,25,2011-01-04 10:00:00,0.42,13313,United Kingdom
2,539993,21498,RED RETROSPOT WRAP,25,2011-01-04 10:00:00,0.42,13313,United Kingdom
3,539993,22379,RECYCLING BAG RETROSPOT,5,2011-01-04 10:00:00,2.10,13313,United Kingdom
4,539993,20718,RED RETROSPOT SHOPPER BAG,10,2011-01-04 10:00:00,1.25,13313,United Kingdom

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 150039 entries, 0 to 203421
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    150039 non-null  object
 1   StockCode    150039 non-null  object
 2   Description  150039 non-null  object
 3   Quantity     150039 non-null  int64
 4   InvoiceDate  150039 non-null  datetime64[ns]
 5   UnitPrice    150039 non-null  float64
 6   CustomerID   150039 non-null  object
 7   Country      150039 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 10.3+ MB

In [14]:
df.duplicated().sum()

np.int64(1490)

In [15]:
df.drop_duplicates(inplace= True)

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
df.describe()

            Quantity                    InvoiceDate      UnitPrice
count  148549.000000                         148549  148549.000000
mean       12.623289  2011-04-06 07:37:53.255962624       3.898172
min    -74215.000000            2011-01-04 10:00:00       0.000000
25%         2.000000            2011-02-22 17:25:00       1.250000
50%         6.000000            2011-04-07 10:20:00       1.950000
75%        12.000000            2011-05-19 17:13:00       3.750000
max     74215.000000            2011-06-30 20:08:00   38970.000000
std       276.503772                            NaN     108.985534

In [18]:
df[df["Quantity"] <= 0]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
76,C540006,21306,SET/4 DAISY MIRROR MAGNETS,-1,2011-01-04 10:48:00,2.10,14606,United Kingdom
77,C540006,84352,SILVER CHRISTMAS TREE BAUBLE STAND,-1,2011-01-04 10:48:00,16.95,14606,United Kingdom
78,C540006,22423,REGENCY CAKESTAND 3 TIER,-1,2011-01-04 10:48:00,12.75,14606,United Kingdom
79,C540007,21055,TOOL BOX SOFT TOY,-6,2011-01-04 11:08:00,8.95,15379,United Kingdom
80,C540007,22274,FELTCRAFT DOLL EMILY,-6,2011-01-04 11:08:00,2.95,15379,United Kingdom
...,...,...,...,...,...,...,...,...
201945,C558531,22424,ENAMEL BREAD BIN CREAM,-1,2011-06-30 11:31:00,12.75,15039,United Kingdom
202318,C558553,23170,REGENCY TEA PLATE ROSES,-576,2011-06-30 12:44:00,1.45,17949,United Kingdom
202427,C558559,20749,ASSORTED COLOUR MINI CASES,-1,2011-06-30 13:20:00,7.95,17648,United Kingdom
202627,C558575,22693,GROW A FLYTRAP OR SUNFLOWER IN TIN,-24,2011-06-30 14:58:00,1.25,12674,France
203075,C558615,21845,DAIRY MAID STRIPE MUG,-4,2011-06-30 16:20:00,0.79,17719,United Kingdom

In [19]:
url1 = 'https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-population.csv'
url2 = 'https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-areas.csv'
url3 = 'https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-abbrevs.csv'

pop = pd.read_csv(url1)
areas = pd.read_csv(url2)
abbrevs = pd.read_csv(url3)

In [20]:
print(pop.head(2))
print(abbrevs.head(2))
print(areas.head(2))

  state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
     state abbreviation
0  Alabama           AL
1   Alaska           AK
     state  area (sq. mi)
0  Alabama          52423
1   Alaska         656425

In [22]:
pop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2544 entries, 0 to 2543
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   state/region  2544 non-null   object
 1   ages          2544 non-null   object
 2   year          2544 non-null   int64
 3   population    2524 non-null   float64
dtypes: float64(1), int64(1), object(2)
memory usage: 79.6+ KB

In [23]:
pop.duplicated().sum()

np.int64(0)

In [24]:
abbrevs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   state         51 non-null     object
 1   abbreviation  51 non-null     object
dtypes: object(2)
memory usage: 948.0+ bytes

In [25]:
abbrevs.duplicated().sum()

np.int64(0)

In [26]:
areas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   state          52 non-null     object
 1   area (sq. mi)  52 non-null     int64
dtypes: int64(1), object(1)
memory usage: 964.0+ bytes

In [27]:
areas.duplicated().sum()

np.int64(0)

In [29]:
print(pop.head(2))
print(abbrevs.head(2))
print(areas.head(2))

  state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
     state abbreviation
0  Alabama           AL
1   Alaska           AK
     state  area (sq. mi)
0  Alabama          52423
1   Alaska         656425

In [33]:
df01 = pd.merge(pop,abbrevs,
         left_on="state/region",
         right_on='abbreviation',
         how='inner')

In [34]:
df01.head()

  state/region     ages  year  population    state abbreviation
0           AL  under18  2012   1117489.0  Alabama           AL
1           AL    total  2012   4817528.0  Alabama           AL
2           AL  under18  2010   1130966.0  Alabama           AL
3           AL    total  2010   4785570.0  Alabama           AL
4           AL  under18  2011   1125763.0  Alabama           AL

In [35]:
areas.head()

        state  area (sq. mi)
0     Alabama          52423
1      Alaska         656425
2     Arizona         114006
3    Arkansas          53182
4  California         163707

In [38]:
df02 = pd.merge(df01,areas)
df02.head()

  state/region     ages  year  population    state abbreviation  area (sq. mi)
0           AL  under18  2012   1117489.0  Alabama           AL          52423
1           AL    total  2012   4817528.0  Alabama           AL          52423
2           AL  under18  2010   1130966.0  Alabama           AL          52423
3           AL    total  2010   4785570.0  Alabama           AL          52423
4           AL  under18  2011   1125763.0  Alabama           AL          52423

In [39]:
df03 = df02[['state','ages','year','population','area (sq. mi)']]
df03.head()

     state     ages  year  population  area (sq. mi)
0  Alabama  under18  2012   1117489.0          52423
1  Alabama    total  2012   4817528.0          52423
2  Alabama  under18  2010   1130966.0          52423
3  Alabama    total  2010   4785570.0          52423
4  Alabama  under18  2011   1125763.0          52423

In [40]:
df03['density'] = df03['population']/df03['area (sq. mi)']

C:\Users\Admin\AppData\Local\Temp\ipykernel_12044\3003707545.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df03['density'] = df03['population']/df03['area (sq. mi)']

In [ ]:
df03.head()

     state     ages  year  population  area (sq. mi)    density
0  Alabama  under18  2012   1117489.0          52423  21.316769
1  Alabama    total  2012   4817528.0          52423  91.897221
2  Alabama  under18  2010   1130966.0          52423  21.573851
3  Alabama    total  2010   4785570.0          52423  91.287603
4  Alabama  under18  2011   1125763.0          52423  21.474601

In [44]:
df04 = df03[(df03['year']==2010)&(df03['ages']=='total')][['state','density']]

In [45]:
df04.head()

          state     density
3       Alabama   91.287603
91       Alaska    1.087509
101     Arizona   56.214497
189    Arkansas   54.948667
197  California  228.051342

In [46]:
df04['Rank'] = df04['density'].rank(ascending=False)
df04.head()

          state     density  Rank
3       Alabama   91.287603  26.0
91       Alaska    1.087509  51.0
101     Arizona   56.214497  34.0
189    Arkansas   54.948667  35.0
197  California  228.051342  12.0

In [47]:
df04.sort_values(by='Rank')

                     state      density  Rank
389   District of Columbia  8898.897059   1.0
1445            New Jersey  1009.253268   2.0
1914          Rhode Island   681.339159   3.0
293            Connecticut   645.600649   4.0
1050         Massachusetts   621.815538   5.0
965               Maryland   466.445797   6.0
379               Delaware   460.445752   7.0
1541              New York   356.094135   8.0
475                Florida   286.597129   9.0
1829          Pennsylvania   275.966651  10.0
1722                  Ohio   257.549634  11.0
197             California   228.051342  12.0
666               Illinois   221.687472  13.0
2213              Virginia   187.622273  14.0
677                Indiana   178.197831  15.0
1626        North Carolina   177.617157  16.0
485                Georgia   163.409902  17.0
2021             Tennessee   150.825298  18.0
1925        South Carolina   144.854594  19.0
1434         New Hampshire   140.799273  20.0
570                 Hawaii   124.746707  21.0
858               Kentucky   107.586994  22.0
1061              Michigan   102.015794  23.0
2298            Washington    94.557817  24.0
2106                 Texas    93.987655  25.0
3                  Alabama    91.287603  26.0
869              Louisiana    87.676099  27.0
2394             Wisconsin    86.851900  28.0
1242              Missouri    86.015622  29.0
2309         West Virginia    76.519582  30.0
2202               Vermont    65.085075  31.0
1157           Mississippi    61.321530  32.0
1146             Minnesota    61.078373  33.0
101                Arizona    56.214497  34.0
189               Arkansas    54.948667  35.0
762                   Iowa    54.202751  36.0
1733              Oklahoma    53.778278  37.0
283               Colorado    48.493718  38.0
1818                Oregon    39.001565  39.0
954                  Maine    37.509990  40.0
773                 Kansas    34.745266  41.0
2117                  Utah    32.677188  42.0
1349                Nevada    24.448796  43.0
1338              Nebraska    23.654153  44.0
581                  Idaho    18.794338  45.0
1530            New Mexico    16.982737  46.0
2010          South Dakota    10.583512  47.0
1637          North Dakota     9.537565  48.0
1253               Montana     6.736171  49.0
2405               Wyoming     5.768079  50.0
91                  Alaska     1.087509  51.0