## Lecture 3: Data Aggregation and Group Operations

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [3]:
planets = sns.load_dataset('planets')
planets.head()

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [4]:
df = pd.DataFrame({'key': list("ABCABC"),
                   "data":range(6)},
                   columns=['key','data'])
df

  key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [7]:
list(df.groupby('key'))

[('A',
    key  data
  0   A     0
  3   A     3),
 ('B',
    key  data
  1   B     1
  4   B     4),
 ('C',
    key  data
  2   C     2
  5   C     5)]

In [9]:
for ob in df.groupby('key'):
    print(ob[1])

  key  data
0   A     0
3   A     3
  key  data
1   B     1
4   B     4
  key  data
2   C     2
5   C     5

In [10]:
df.groupby('key').sum()

     data
key
A       3
B       5
C       7

In [11]:
planets.head()

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [12]:
planets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1035 entries, 0 to 1034
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   method          1035 non-null   object
 1   number          1035 non-null   int64
 2   orbital_period  992 non-null    float64
 3   mass            513 non-null    float64
 4   distance        808 non-null    float64
 5   year            1035 non-null   int64
dtypes: float64(3), int64(2), object(1)
memory usage: 48.6+ KB

In [13]:
planets.duplicated().sum()

np.int64(4)

In [14]:
planets.drop_duplicates(inplace=True)

In [17]:
planets[['method','number']].groupby('method').sum().sort_values(by='number',ascending=False)

                               number
method
Radial Velocity                   952
Transit                           776
Imaging                            49
Microlensing                       23
Eclipse Timing Variations          15
Pulsar Timing                      11
Transit Timing Variations           9
Orbital Brightness Modulation       5
Astrometry                          2
Pulsation Timing Variations         1

In [23]:
planets[['year','mass','number','orbital_period']].info()

<class 'pandas.core.frame.DataFrame'>
Index: 1031 entries, 0 to 1034
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   year            1031 non-null   int64
 1   mass            513 non-null    float64
 2   number          1031 non-null   int64
 3   orbital_period  992 non-null    float64
dtypes: float64(2), int64(2)
memory usage: 40.3 KB

In [21]:
# groupby by year:
# sum of number; means of mass, min and max of orbital_period 
planets[['year','mass','number','orbital_period']].groupby('year').aggregate({'mass':'mean',
                                                                              'number':'sum',
                                                                              'orbital_period':['min','max']})

           mass number orbital_period
           mean    sum            min            max
year
1989  11.680000      1      83.888000      83.888000
1992        NaN      6      25.262000      66.541900
1994        NaN      3      98.211400      98.211400
1995   0.472000      1       4.230785       4.230785
1996   1.979400     15       3.313500    1078.000000
1997   1.040000      1      39.845000      39.845000
1998   2.687120     11       3.097000     442.100000
1999   3.236643     24       3.510000    3810.000000
2000   3.633014     27       3.024000    2502.000000
2001   3.430909     15       6.276000    2391.000000
2002   3.937290     46       1.211919    4909.000000
2003   3.660955     35       1.328300   36525.000000
2004   1.454267     41       1.432475    4205.800000
2005   2.003897     64       1.937780    4270.000000
2006   1.799800     43       1.796000  730000.000000
2007   3.702094     65       1.306186    1333.000000
2008   3.424339    118       1.091423  318280.000000
2009   3.628568    130       0.788840   17337.500000
2010   1.289610    193       1.212884   18000.000000
2011   1.209084    354       0.090706   40000.000000
2012   3.658596    256       0.742960    6005.000000
2013   2.203400    277       0.355000    4100.000000
2014   1.068000    117       0.669310    3827.000000

In [ ]:
planets[['method','number']].groupby('method').sum()
planets.groupby('method')[['number']].sum()

                               number
method
Astrometry                          2
Eclipse Timing Variations          15
Imaging                            49
Microlensing                       23
Orbital Brightness Modulation       5
Pulsar Timing                      11
Pulsation Timing Variations         1
Radial Velocity                   952
Transit                           776
Transit Timing Variations           9

In [20]:
planets.groupby('method')[['number']].sum()

                               number
method
Astrometry                          2
Eclipse Timing Variations          15
Imaging                            49
Microlensing                       23
Orbital Brightness Modulation       5
Pulsar Timing                      11
Pulsation Timing Variations         1
Radial Velocity                   952
Transit                           776
Transit Timing Variations           9

In [22]:
planets[['year','mass','number','orbital_period']].info()

<class 'pandas.core.frame.DataFrame'>
Index: 1031 entries, 0 to 1034
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   year            1031 non-null   int64
 1   mass            513 non-null    float64
 2   number          1031 non-null   int64
 3   orbital_period  992 non-null    float64
dtypes: float64(2), int64(2)
memory usage: 40.3 KB

In [28]:
planets.groupby('method').filter(lambda x: x['number'].sum()>=20)

               method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1007 rows x 6 columns]